### ISSUE TITLE
't' in permissions

### ISSUE THREAD

**Issue by d4os** [codebynumbers/ftpretty#29]
I've encountered a problem in listing contents of a ftp server:
sample code:
```
from ftpretty import ftpretty
ftp = ftpretty(host, user, password)
print ftp.list(extra=True)
```
The output is 
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.4\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.4\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.4\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "<cut>ftp.py", line 8, in <module>
    print ftp.list(extra=True)
  File "C:\Python27\lib\site-packages\ftpretty.py", line 160, in list
    directory_list = split_file_info(self.tmp_output)
  File "C:\Python27\lib\site-packages\ftpretty.py", line 245, in split_file_info
    date = parts[7]
IndexError: list index out of range
```
The line it has problems is 
`'drwxrwxrwt   2 999      999          4096 Sep  9 11:15 tmp'`
what I've found about it is 
[So what is the sticky bit?](https://askubuntu.com/a/432703)

I think changing 
`r'([\-rwxs]{9})\s+' +               # Permissions [2]`
to
`r'([\-rwxst]{9})\s+' +               # Permissions [2]`
should fix it.

**Comment by codebynumbers** [comment]
Nice catch pushing a fix shorty.

**Comment by codebynumbers** [comment]
Fixed in 0.2.8

**Comment by d4os** [comment]
Unfortunately it's still not working, the 't' letter is 9th letter of permissions (or 8th in computer speech), the test should be
`drwxr-xr-t`
 instead of 
`drwxr-xr-xt`
the 't' isn't an extra letter, it replaces the 'x'. I've made additional research, it turns out [uppercase 'T' also exists](https://unix.stackexchange.com/a/228927), but even that is not all because [uppercase 'S' is also possible](https://en.wikipedia.org/wiki/File_system_permissions), my suggestion would therefore be:
` r'((?:[r-][w-][-xsStT]){3})\s+' + # Permissions [2]`
as seen [here: regexr.com/4klno](https://regexr.com/4klno)

Thanks for the quick response, after creating that issue I've had some fun with ftpretty and it's great.
